# Site settings
course_name: Artificial Neural Networks
course_description:
"
<h4> Neural Networks </h4>
The goal of “Neural Networks” is to realize artificial intelligent systems using the human brain as the model. In this course, we will introduce the basics of neurons and network models, learning algorithms, architectures, and some applications of neural networks. At the end of this course, students will be able to use neural networks for solving different problems related to pattern recognition, function approximation, data visualization, and so on. Basically, students will learn how to answer the following questions for a given problem:

* What kind of structure or model should they use? 
* How to train or design the neural network? 
* How to use neural networks for knowledge acquisition? 
"
course_semester: "Fall 2020"

baseurl: "/CS-SBU-ANN-Bsc-3991" # the subpath of your site, e.g. /blog/
url: "http://alisharifi2000.github.io/" # the base hostname & protocol for your site

schoolname: "Shahid Beheshti University"
schoolurl: "https://sbu.ac.ir"
#twitter_username: username 

address: |
    Shahid Beheshti University,
    Shahid Shahriari Square,
    Daneshjou Boulevard,
    Shahid Chamran Highway,
    Tehran, Iran

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-81SM43E48E

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css', '_js']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
